# Generated by Django 5.2.12 on 2026-04-01 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "batch_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="批次ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(blank=True, max_length=64, verbose_name="订单号"),
                ),
                (
                    "fabric_weight_gsm",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="坯布克重(g/m²)"
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="门幅(cm)"
                    ),
                ),
                (
                    "fiber_type",
                    models.CharField(
                        choices=[
                            ("PET", "PET"),
                            ("Cotton", "Cotton"),
                            ("Nylon", "Nylon"),
                            ("PLA", "PLA"),
                            ("PET/Cotton", "PET/Cotton"),
                        ],
                        max_length=32,
                        verbose_name="纤维种类",
                    ),
                ),
                (
                    "fiber_structure",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="纤维结构"
                    ),
                ),
                (
                    "weave_type",
                    models.CharField(
                        choices=[
                            ("平纹", "平纹"),
                            ("斜纹", "斜纹"),
                            ("缎纹", "缎纹"),
                            ("针织", "针织"),
                        ],
                        max_length=32,
                        verbose_name="织法",
                    ),
                ),
                (
                    "pretreatment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="前处理效果评分",
                    ),
                ),
                (
                    "liquor_ratio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="浴比(L/kg)"
                    ),
                ),
                (
                    "load_amount_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="装载量(kg)"
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(max_length=64, verbose_name="操作员"),
                ),
                ("machine_id", models.CharField(max_length=64, verbose_name="缸号")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "批次主表",
                "verbose_name_plural": "批次主表",
                "ordering": ["-created_at", "-batch_id"],
            },
        ),
        migrations.CreateModel(
            name="ChemicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chemical_type",
                    models.CharField(
                        choices=[("染料", "染料"), ("助剂", "助剂")],
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                (
                    "chemical_name",
                    models.CharField(max_length=128, verbose_name="名称"),
                ),
                (
                    "concentration_gpl",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="浓度(g/L)"
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="检测方法"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals",
                        to="dyeing.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "化学品表",
                "verbose_name_plural": "化学品表",
            },
        ),
        migrations.CreateModel(
            name="EnvironmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "water_ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="水pH",
                    ),
                ),
                (
                    "water_conductivity_us_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="水电导率(μS/cm)",
                    ),
                ),
                (
                    "water_hardness_mgL",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="硬度(mg/L)",
                    ),
                ),
                (
                    "water_cod_mgL",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="COD(mg/L)",
                    ),
                ),
                (
                    "equipment_status",
                    models.CharField(
                        choices=[
                            ("正常", "正常"),
                            ("待机", "待机"),
                            ("维护", "维护"),
                            ("故障", "故障"),
                        ],
                        max_length=16,
                        verbose_name="设备状态",
                    ),
                ),
                (
                    "vibration_mm_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="振动(mm/s)",
                    ),
                ),
                (
                    "equipment_temp_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="设备温度(℃)",
                    ),
                ),
                (
                    "sop_compliance",
                    models.CharField(
                        blank=True,
                        choices=[("高", "高"), ("中", "中"), ("低", "低")],
                        max_length=16,
                        verbose_name="SOP执行一致性",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment",
                        to="dyeing.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "环境设备表",
                "verbose_name_plural": "环境设备表",
            },
        ),
        migrations.CreateModel(
            name="ResultRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dye_time_min", models.IntegerField(verbose_name="染色时间(min)")),
                (
                    "ks_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="K/S",
                    ),
                ),
                (
                    "reflectance_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="反射率(%)",
                    ),
                ),
                (
                    "delta_e_2000",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="色差ΔE2000"
                    ),
                ),
                (
                    "spectrum_curve_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="色光谱曲线(JSON)"
                    ),
                ),
                (
                    "result_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="L",
                    ),
                ),
                (
                    "result_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="a",
                    ),
                ),
                (
                    "result_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="b",
                    ),
                ),
                (
                    "rft_flag",
                    models.CharField(
                        choices=[("是", "是"), ("否", "否")],
                        max_length=8,
                        verbose_name="是否一次成功",
                    ),
                ),
                (
                    "rework_count",
                    models.IntegerField(default=0, verbose_name="复修次数"),
                ),
                (
                    "energy_steam_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="能耗(kg蒸汽)",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="dyeing.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "结果表",
                "verbose_name_plural": "结果表",
            },
        ),
        migrations.CreateModel(
            name="ProcessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_min", models.IntegerField(verbose_name="时间(min)")),
                (
                    "temperature_c",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="温度(℃)"
                    ),
                ),
                (
                    "heating_rate_cpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="升降温速率(℃/min)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="pH",
                    ),
                ),
                (
                    "conductivity_ms_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="电导率(mS/cm)",
                    ),
                ),
                (
                    "flow_rate_lpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="流速(L/min)",
                    ),
                ),
                (
                    "dye_concentration_gpl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="染料浓度(g/L)",
                    ),
                ),
                (
                    "dye_uptake_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="上染率/吸尽率(%)",
                    ),
                ),
                (
                    "stirring_intensity_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="搅拌强度(rpm)",
                    ),
                ),
                (
                    "dye_concentration_spectrum",
                    models.JSONField(
                        blank=True, null=True, verbose_name="染料浓度光谱数据(JSON)"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_records",
                        to="dyeing.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "工艺时序表",
                "verbose_name_plural": "工艺时序表",
                "ordering": ["batch_id", "time_min"],
                "unique_together": {("batch", "time_min")},
            },
        ),
    ]
